README.md
src/GooglePlacesAutocomplete/index.js
src/utils/customPropTypes.js
src/utils/debounce.js

Add autocompletion request prop

---

README.md
package.json
src/utils/customPropTypes.js

Fix bounds prop validation

---

package-lock.json
src/GooglePlacesAutocomplete/index.js
src/utils/autocompletionRequestBuilder.js

Create a  for the location property

---

src/GooglePlacesAutocomplete/index.js

Potential issue where the maps would not have loaded yet, causing an undefined error.
Closes #18

InitializeService missing maps condition

---

package.json
src/GooglePlacesAutocomplete/index.js

* Fixed a typo in renderSuggestions()

Fixed a typo in renderSuggestions()

---

README.md
package.json
src/GooglePlacesAutocomplete/index.js

Here are the changes:
- Version up-ed to 1.5.3
- Added a disabled prop.
- Previously, required prop was added but it wasn't added to the actually rendered input itself.
- Fixed some linting.
Please let me know if any changes need to be made :)

Disabled Prop + Minor fixes

---

README.md

Update renderSuggestion documentation

---

README.md
src/GooglePlacesAutocomplete/index.js

Add idPrefix prop

---

src/GooglePlacesAutocomplete/index.js

change componentWillReceiveProps to UNSAFE_componentWillReceiveProps 

---

package.json
src/GooglePlacesAutocomplete/index.js
src/index.d.ts

Add Typescript definition files

---

README.md

The yarn command was missing the action `add`

Update yarn install command

---

src/index.d.ts

Fix TS typings

---

src/GooglePlacesAutocomplete/index.js

Clear timeout on componentWillUnmount

---

src/GooglePlacesAutocomplete/index.js
src/helpers/injectScript.js

Remove 'removeScript' call

---

src/GooglePlacesAutocomplete/index.js

allow custom suggestion to appear even if there is no google suggestion return

---

src/GooglePlacesAutocomplete/index.js

[issue][89] Workaround to fix issue #89

---

babel.config.js
package.json
yarn.lock

Fix 'regeneratorRuntime is not defined'

---

src/GooglePlacesAutocomplete/index.js

Set the active suggestion on mouse hover

---

.npmignore
README.md
src/GooglePlacesAutocomplete.types.tsx
src/utils/getLatLng.ts

Closes #112 
Changes:
- Add .npmignore
- Add return type to `getLatLng`

[issue][112] Add .npmignore to only publish build folder

---

docs/docs/props.md

i removed the comma `;` after the console log on `onLoadFailed` prop

Docs: Modified Typo

---

docs/docs/geocode-by-lat-long.md
docs/sidebars.js
src/index.ts
src/utils/geocodeByLatLng.ts
src/utils/geocodeByPlaceId.ts

[feature/reverse-geocoding] Add util function to geocode an address from { lat: number, lng: number }

---

package.json

Update peer dependecies. Closes #139

[issue/139] udpate peer dependencies

---

docs/docs/geocode-by-lat-long.md
docs/sidebars.js
docs/yarn.lock
package.json
src/index.ts
src/utils/geocodeByLatLng.ts
src/utils/geocodeByPlaceId.ts

Release 3.1.0

---

package.json
rollup.config.js
yarn.lock

Reduce bundle size by ~half
Before:
After:
Closes #123

chore: add terser to reduce bundle size

---

docs/docs/exposed-methods.md
docs/sidebars.js
src/GooglePlacesAutocomplete.tsx
src/GooglePlacesAutocomplete.types.tsx
tsconfig.json

feat: expose session token

---

package.json
yarn.lock

issue/206: bump react-select to 4.3.1
